version: '3.9'

services:
  app:
    build: ./
    restart: "always"
    ports:
      - "8001:3000"
    environment:
      - MONGO_DBURL=mongodb+srv://220159:220159password@cluster0.0ipredr.mongodb.net/frs_app?retryWrites=true&w=majority
